security:
  basic.enabled: false

endpoints:
  enabled: false
  jmx.enabled: false
  env.enabled: true
  configprops.enabled: true

logging:
  level:
    org.springframework: INFO
    org.hibernate: INFO
    
---

spring:
  profiles: cloud
security:
  require-ssl: false